---
- name: System Configuration Checks
  hosts: node1
  become: true
  gather_facts: false
  tasks:
    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        minutes: 5

    - name: Check user existence
      ansible.builtin.command:
        cmd: id ec2-user
      register: user_check
 
    - name: Report user status
      ansible.builtin.debug:
        msg: "User 'myuser' exists."
      when: user_check.rc == 0
